apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s-%s-%s" .Values.project .Values.clientname .Values.envname .Values.appname }}
  namespace: {{ printf "%s-%s-%s" .Values.project .Values.clientname .Values.envname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: {{ .Values.appname }}
          image: 10.10.56.33/{{ .Values.project }}-tes/{{ .Values.appname }}-{{ .Values.envname }}:{{ .Values.imageTag }}
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-%s-%s-service" .Values.project .Values.clientname .Values.envname .Values.appname }}
  namespace: {{ printf "%s-%s-%s" .Values.project .Values.clientname .Values.envname }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appname }}
  ports:
    - port: 80
      targetPort: 80
